### ISSUE TITLE
undefined method `callback'

### ISSUE THREAD

**Issue by YassineDM** [jdliss/shoulda-callback-matchers#30]
I got this error message with a callback, which does not seem to be related to Spring as mentioned in the [doc](https://github.com/jdliss/shoulda-callback-matchers#undefined-method-callback):
```
Failure/Error: it { is_expected.to callback(:after_create_callback).after(:create) }
     
NoMethodError:
  undefined method `callback' for #<RSpec::ExampleGroups::UserAccount::Callbacks::FiresCallbacks:0x00007fbab10cba48>
# ./spec/models/user_account_spec.rb:80:in `block (4 levels) in <top (required)>'
# ./spec/rails_helper.rb:69:in `block (3 levels) in <top (required)>'
# ./spec/rails_helper.rb:68:in `block (2 levels) in <top (required)>'
```
Here is how Shoulda Matchers are configured in rails_helper.rb:
```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```
In Gemfile:
```ruby
gem 'rails', '~> 6.0.2'

group :development, :test do
  gem 'rspec-rails', '~> 3.8'
  # ...
end

group :test do
  gem 'shoulda-matchers'
  # ...
end
```

**Comment by chrisgeek** [comment]
@YassineDM I think the Readme says 
```
group :test do
  gem 'shoulda-callback-matchers', '~> 1.1.1'
end
```
and not
```
group :test do
  gem 'shoulda-matchers'
end
```

**Comment by YassineDM** [comment]
@chrisgeek, you're right, it is now perfectly working. Sorry for this careless mistake...
